- JINHO/BJ1001.java
- JINHO/BJ10172.java
- JINHO/BJ10718.java
- JINHO/BJ11718.java
- JINHO/BJ2557.java
- JINHO/BJ5339.java
- JINHO/BJ7287.java
- JINHO/BJ9316.java
- JINHO/Bj9654.java
- JINHO/Main.java
> [Solve] BJ10718 - We love kriii

- JINHO/BJ2739.java
- BJ2739
- 띄어쓰기 안했다가 한번 틀렸읍니다..
> [Solve] BJ2739 - 구구단

- JINHO/BJ2439.java
> [Solve] BJ2439 - 별 찍기 2

- SIHYUN/BJ11720.java
- BJ11720
- 열심히 풀었습니당 (feat, 미진호)
> [Solve] BJ11720 - 숫자의 합

- JINHO/BJ10926.java
> [Solve] BJ10926 - ??!

- SIHYUN/BJ1546.java
- BJ1546 - 평균
-  입력받은 값은 배열에 넣어주고, 반복문을 통하여 평균, 최댓값을 구하여 문제에서 요구하는 바를 해결함.
> [Solve] BJ1546 - 평균

- SIHYUN/BJ2577.java
> [Solve] BJ2577 - 숫자의 개수

- JINHO/BJ3003.java
- BJ3003
- 배열 입력받아서 체스 말의 개수만큼 빼서 부족한 수가 몇인지 보는 코드임다
> [Solve] BJ3003 - 킹, 퀸, 룩, 비숍, 나이트, 폰

- JINHO/BJ1330.java
> [Solve] BJ1330 - 두 수 비교하기

- JINHO/BJ25314.java
- BJ25314
- N값을 4 이상으로 받고 append로 문자열 붙여서 출력했습니다~
> [Solve] BJ25314 - 코딩은 체육과목 입니다

- SIHYUN/BJ1712.java
- BJ1712
- https://www.notion.so/jeong-ios/BJ1712-691a26928e044f138d56f87ab8131b20 <-- 이거 보시면 됩니다.
> [Solve] BJ1712 - 순익분기점

- SIHYUN/BJ1978.java
- BJ1978
- j가 입력받은 정수을 초과하지 않는 최대 제곱수까지 j로 나누어 소수를 구별하는 방법을 이용함.
> [Solve] BJ1978 - 소수 찾기

- JINHO/BJ10807.java
- JINHO/BJ18108.java
> [Solve] BJ18108 - 1998년생인 내가 태국에서는 2541년생?!

- JINHO/BJ10807.java
- BJ10807
- 배열에 입력받을 개수 담고 확인할 수를 배열에 조건문 성립할 때 마다 1+= 해서 출력했습니다~
> [Solve] BJ10807 - 개수 세기

- SIHYUN/BJ2839.java
- BJ2839
- 3과 5중 5로 먼저 나누고, 나누어 떨어지지 않을 경우 정수 N에서 -3 을 하여 반복적으로 5로 나눌 수 있을때까지 함.
- -3 한것은 three 라는 새 변수에 +1 들어가게하여 나중에 결과값에 추가하여 반영함.
> [Solve] BJ2839 -  설탕 배달

- JINHO/BJ2753.java
> [Solve] BJ2753 - 윤년

- SIHYUN/BJ2869.java
- BJ2869
- 고민하다 머리 터져서 인터넷 봤습니다. ( 해결실패... )
- https://www.notion.so/jeong-ios/BJ2869-c5de1cb032134bb39cd8513ea5ec095e
- 여러분들도 한 번 풀어봐서 알려주세요
> [Solve] BJ2869 - 달팽이는 올라가고 싶다.

- JINHO/BJ2438.java
- BJ2438
- 날먹은 오늘까지만 하겠습니다 인생이 힘드네요
> [Solve] BJ2438 - 별 찍기 - 1

- SIHYUN/BJ2675.java
- BJ2675
- 반복문 사용해서 문자를 반복으로 돌렸습니다.
- 왠지 더 좋은 방법이 있을것 같은 느낌이 드는데... 흐음...
-
> [Solve] BJ2675 - 문자열 반복

- SIHYUN/BJ2750.java
> [Solve] BJ2750 - 수 정렬하기

- SIHYUN/BJ5622.java
> [Solve] BJ5622 - 다이얼

- SIHYUN/BJ10817.java
- BJ10817
- 배열의 정렬을 사용하여 간단하게 표현했습니다.
> [Solve] BJ10817 - 세 수

- SIHYUN/BJ10250.java
- BJ10250
- 2차원 배열을 사용하여 문제를 풀었습니다.
- https://www.notion.so/kwonjeong/BJ10250-ACM-de91bbdd17f04ba8a39c9a4fd6a3f44a
- (살짝 하드코딩 인것 같기도...)
> [Solve] BJ10250 - ACM 호텔

- SIHYUN/BJ10773.java
- BJ10773
- 자바에서 제공하는 라이브러리 Stack 배열 사용하여 문제 해결.
- https://www.notion.so/kwonjeong/BJ10773-1cb108fe637c456b95b6888597510cf1
> [Solve] BJ10773 - 제로

- SIHYUN/BJ2920.java
- BJ2920
- https://www.notion.so/kwonjeong/BJ2920-1d8f472645ee401a8dc2b723ffa81983
> [Solve] BJ2920 - 음계

- SIHYUN/BJ10809.java
- BJ10809 
- 문제의 난이도보다 처음보는 메소드이기에 중요하다 생각하여 올립니다.
- indexOf -> 찾을 특정문자가 몇 번째의 인덱스에 존재하는지 알려주는 메소드
> [Solve] BJ10809 - 알파벳 찾기

- SIHYUN/BJ1620.java
- BJ1620
- 'key-value' 형태로 저장하는 hashmap(파이썬 dict이랑 비슷합니다.) 을 사용하여 문제해결.
- https://www.notion.so/kwonjeong/BJ1620-14fee4ce5c9746798dd42ecc83ef4367
> [Solve] BJ1620 - 나는야 포켓몬 마스터 이다솜

- SIHYUN/BJ1924.java
- BJ1924
- https://www.notion.so/kwonjeong/BJ1924-2007-14153239ef8643fa819accf24bf9235d
> [Solve] BJ1924 - 2007년

- SIHYUN/BJ11721.java
- BJ11721
- https://www.notion.so/kwonjeong/BJ11721-1177fc3acced4a1fa07f285c65930b7a
> [Solve] BJ11721 - 열 개씩 끊어 출력하기

- SIHYUN/BJ1193.java
- BJ1193 - 분수찾기
- https://www.notion.so/kwonjeong/BJ1193-a685cec09cfc494d96f5b599d802bd9e [ 노션 참고하세요. ]
> [Solve] BJ1193 - 분수찾기

- JINHO/BJ14681.java
> [Solve] BJ14681 - 사분면 고르기

- JINHO/BJ14681.java
- JINHO/BJ27866.java
> [Solve] BJ27866 - 문자와 문자열

- JINHO/BJ27866.java
- JINHO/BJ9498.java
- BJ9498
- 1학년 1학기 첫째주가 생각이 나는 문제네요
> [Solve] BJ9498 - 시험 성적

- JINHO/BJ10951.java
- JINHO/BJ25304.java
> [Solve] BJ10951 - A + B - 4

- SIHYUN/BJ2775.java
- BJ2775
- 아래 사진에 나와있는 것처럼 규칙을 찾아서 그대로 코딩에 적용시켜 문제를 해결함.
> [Solve] BJ2775 - 부녀회장이 될테야

- SIHYUN/BJ10870_DP.java
> [Update] BJ10870 - 피보나치 수 5 ( 재풀이 )

- JINHO/BJ10951.java
- JINHO/BJ11021.java
> [Solve] BJ11021 - A + B - 7

- JINHO/BJ10952.java
> [Solve] BJ10952 - A + B - 5

- JINHO/BJ2588.java
> [Solve] BJ2588 - 곱셈

- SIHYUN/BJ3009.java
- BJ3009
- 입력받은 x좌표와 y좌표 3개 중에서 값이 다른 하나가 네 번째점의 x좌표와 y좌표이다.
- 이 규칙을 이용하여 if문을 사용하여 값을 넣어주었다.
> [Solve] BJ3009 - 네 번째 점

- SIHYUN/BJ10162.java
- BJ10162
- BJ2839 (설탕배달) 의 순한맛 버전이네요. / 같은 방법으로 문제를 해결하면 됩니다
> [Solve] BJ10162 - 전자레인지
